main = "./src/index.ts"
name = "cart"
compatibility_date = "2022-07-26"

[env.dev]
worker_dev = true
routes = [{ pattern = "localhost:8787/*", zone_id= ""}, { pattern = "localhost:8787/", zone_id= ""}]
kv_namespaces = [
  { binding = "CART", id = "974de73114ca4b07a89195841bbb62de", preview_id = "9c0c5f2e584344a89b2fe32eaa3667bd" }
]
[env.dev.var]

[env.production]
kv_namespaces = [
  { binding = "CART", id = "30e6876caf354a0b8fbde0b0f1ca3dfc" }
]
[env.production.var]
